export enum TransactionType {
  // UPDATE_FISH_SEED = 0,
  // DEPLOY_CONTRACT = 1,
  // UPDATE_ORDER_STATUS = 2,
  // UPDATE_FISH_GROWTH = 3,
  // UPDATE_PROCESSING_CONTRACT = 4,
  // UPDATE_PRODUCT = 5,
  // CREATE_ORDER = 6,
  FISH_SEED = 1,
  CONTRACT = 2,
  FISH_GROWTH = 3,
  ORDER = 4,
  PRODUCT = 5,
}
